// Generated by gencpp from file object_information_msgs/Object.msg
// DO NOT EDIT!


#ifndef OBJECT_INFORMATION_MSGS_MESSAGE_OBJECT_H
#define OBJECT_INFORMATION_MSGS_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Vector3.h>

namespace object_information_msgs
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : header()
    , detect_sequence(0)
    , object_total(0)
    , object_sequence(0)
    , label()
    , probability(0.0)
    , position()
    , size()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detect_sequence(0)
    , object_total(0)
    , object_sequence(0)
    , label(_alloc)
    , probability(0.0)
    , position(_alloc)
    , size(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _detect_sequence_type;
  _detect_sequence_type detect_sequence;

   typedef uint16_t _object_total_type;
  _object_total_type object_total;

   typedef uint16_t _object_sequence_type;
  _object_sequence_type object_sequence;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef float _probability_type;
  _probability_type probability;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::object_information_msgs::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_information_msgs::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::object_information_msgs::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::object_information_msgs::Object > ObjectPtr;
typedef boost::shared_ptr< ::object_information_msgs::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_information_msgs::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_information_msgs::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_information_msgs::Object_<ContainerAllocator1> & lhs, const ::object_information_msgs::Object_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detect_sequence == rhs.detect_sequence &&
    lhs.object_total == rhs.object_total &&
    lhs.object_sequence == rhs.object_sequence &&
    lhs.label == rhs.label &&
    lhs.probability == rhs.probability &&
    lhs.position == rhs.position &&
    lhs.size == rhs.size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_information_msgs::Object_<ContainerAllocator1> & lhs, const ::object_information_msgs::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_information_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_information_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_information_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_information_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_information_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_information_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_information_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_information_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d8f12d51af0cd884816fbc62b3e1cd4";
  }

  static const char* value(const ::object_information_msgs::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d8f12d51af0cd88ULL;
  static const uint64_t static_value2 = 0x4816fbc62b3e1cd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_information_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_information_msgs/Object";
  }

  static const char* value(const ::object_information_msgs::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_information_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Face bounding box with marker positions\n"
"Header header\n"
"uint64 detect_sequence\n"
"uint16 object_total\n"
"uint16 object_sequence\n"
"string label\n"
"float32 probability\n"
"geometry_msgs/Pose position\n"
"geometry_msgs/Vector3 size\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::object_information_msgs::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_information_msgs::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detect_sequence);
      stream.next(m.object_total);
      stream.next(m.object_sequence);
      stream.next(m.label);
      stream.next(m.probability);
      stream.next(m.position);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_information_msgs::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_information_msgs::Object_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detect_sequence: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.detect_sequence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_total: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.object_total);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_sequence: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.object_sequence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "probability: ";
    Printer<float>::stream(s, indent + "  ", v.probability);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_INFORMATION_MSGS_MESSAGE_OBJECT_H
